//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SysproConnector.SysproUtilityService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="utilitiesclassSoap", Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class utilitiesclass : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LogonOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogoffOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLogonProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback RunOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public utilitiesclass() {
            this.Url = global::SysproConnector.Properties.Settings.Default.SysproConnector_SysproUtilityService_utilitiesclass;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LogonCompletedEventHandler LogonCompleted;
        
        /// <remarks/>
        public event LogoffCompletedEventHandler LogoffCompleted;
        
        /// <remarks/>
        public event GetLogonProfileCompletedEventHandler GetLogonProfileCompleted;
        
        /// <remarks/>
        public event RunCompletedEventHandler RunCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.syspro.com/ns/utilities/Logon", RequestNamespace="http://www.syspro.com/ns/utilities/", ResponseNamespace="http://www.syspro.com/ns/utilities/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Logon(string Operator, string OperatorPassword, string CompanyId, string CompanyPassword, Language LanguageCode, LogDetail LogLevel, Instance EncoreInstance, string XmlIn) {
            object[] results = this.Invoke("Logon", new object[] {
                        Operator,
                        OperatorPassword,
                        CompanyId,
                        CompanyPassword,
                        LanguageCode,
                        LogLevel,
                        EncoreInstance,
                        XmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LogonAsync(string Operator, string OperatorPassword, string CompanyId, string CompanyPassword, Language LanguageCode, LogDetail LogLevel, Instance EncoreInstance, string XmlIn) {
            this.LogonAsync(Operator, OperatorPassword, CompanyId, CompanyPassword, LanguageCode, LogLevel, EncoreInstance, XmlIn, null);
        }
        
        /// <remarks/>
        public void LogonAsync(string Operator, string OperatorPassword, string CompanyId, string CompanyPassword, Language LanguageCode, LogDetail LogLevel, Instance EncoreInstance, string XmlIn, object userState) {
            if ((this.LogonOperationCompleted == null)) {
                this.LogonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogonOperationCompleted);
            }
            this.InvokeAsync("Logon", new object[] {
                        Operator,
                        OperatorPassword,
                        CompanyId,
                        CompanyPassword,
                        LanguageCode,
                        LogLevel,
                        EncoreInstance,
                        XmlIn}, this.LogonOperationCompleted, userState);
        }
        
        private void OnLogonOperationCompleted(object arg) {
            if ((this.LogonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogonCompleted(this, new LogonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.syspro.com/ns/utilities/Logoff", RequestNamespace="http://www.syspro.com/ns/utilities/", ResponseNamespace="http://www.syspro.com/ns/utilities/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Logoff(string UserId) {
            object[] results = this.Invoke("Logoff", new object[] {
                        UserId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LogoffAsync(string UserId) {
            this.LogoffAsync(UserId, null);
        }
        
        /// <remarks/>
        public void LogoffAsync(string UserId, object userState) {
            if ((this.LogoffOperationCompleted == null)) {
                this.LogoffOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoffOperationCompleted);
            }
            this.InvokeAsync("Logoff", new object[] {
                        UserId}, this.LogoffOperationCompleted, userState);
        }
        
        private void OnLogoffOperationCompleted(object arg) {
            if ((this.LogoffCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogoffCompleted(this, new LogoffCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.syspro.com/ns/utilities/GetLogonProfile", RequestNamespace="http://www.syspro.com/ns/utilities/", ResponseNamespace="http://www.syspro.com/ns/utilities/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLogonProfile(string UserId) {
            object[] results = this.Invoke("GetLogonProfile", new object[] {
                        UserId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLogonProfileAsync(string UserId) {
            this.GetLogonProfileAsync(UserId, null);
        }
        
        /// <remarks/>
        public void GetLogonProfileAsync(string UserId, object userState) {
            if ((this.GetLogonProfileOperationCompleted == null)) {
                this.GetLogonProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLogonProfileOperationCompleted);
            }
            this.InvokeAsync("GetLogonProfile", new object[] {
                        UserId}, this.GetLogonProfileOperationCompleted, userState);
        }
        
        private void OnGetLogonProfileOperationCompleted(object arg) {
            if ((this.GetLogonProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLogonProfileCompleted(this, new GetLogonProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.syspro.com/ns/utilities/Run", RequestNamespace="http://www.syspro.com/ns/utilities/", ResponseNamespace="http://www.syspro.com/ns/utilities/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Run(string UserId, string BusinessObject, string Parameter) {
            object[] results = this.Invoke("Run", new object[] {
                        UserId,
                        BusinessObject,
                        Parameter});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RunAsync(string UserId, string BusinessObject, string Parameter) {
            this.RunAsync(UserId, BusinessObject, Parameter, null);
        }
        
        /// <remarks/>
        public void RunAsync(string UserId, string BusinessObject, string Parameter, object userState) {
            if ((this.RunOperationCompleted == null)) {
                this.RunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRunOperationCompleted);
            }
            this.InvokeAsync("Run", new object[] {
                        UserId,
                        BusinessObject,
                        Parameter}, this.RunOperationCompleted, userState);
        }
        
        private void OnRunOperationCompleted(object arg) {
            if ((this.RunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RunCompleted(this, new RunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public enum Language {
        
        /// <remarks/>
        AUTO,
        
        /// <remarks/>
        ENGLISH_US,
        
        /// <remarks/>
        FRENCH_CANADIAN,
        
        /// <remarks/>
        DANISH,
        
        /// <remarks/>
        DUTCH,
        
        /// <remarks/>
        ENGLISH,
        
        /// <remarks/>
        FINNISH,
        
        /// <remarks/>
        FRENCH,
        
        /// <remarks/>
        GERMAN,
        
        /// <remarks/>
        ITALIAN,
        
        /// <remarks/>
        NORWEGIAN,
        
        /// <remarks/>
        PORTUGUESE,
        
        /// <remarks/>
        SPANISH,
        
        /// <remarks/>
        SWEDISH,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public enum LogDetail {
        
        /// <remarks/>
        ldNoDebug,
        
        /// <remarks/>
        ldDebug,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public enum Instance {
        
        /// <remarks/>
        EncoreInstance_0,
        
        /// <remarks/>
        EncoreInstance_1,
        
        /// <remarks/>
        EncoreInstance_2,
        
        /// <remarks/>
        EncoreInstance_3,
        
        /// <remarks/>
        EncoreInstance_4,
        
        /// <remarks/>
        EncoreInstance_5,
        
        /// <remarks/>
        EncoreInstance_6,
        
        /// <remarks/>
        EncoreInstance_7,
        
        /// <remarks/>
        EncoreInstance_8,
        
        /// <remarks/>
        EncoreInstance_9,
        
        /// <remarks/>
        EncoreInstanceTostring_10,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void LogonCompletedEventHandler(object sender, LogonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void LogoffCompletedEventHandler(object sender, LogoffCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogoffCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogoffCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetLogonProfileCompletedEventHandler(object sender, GetLogonProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLogonProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLogonProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void RunCompletedEventHandler(object sender, RunCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591