//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SysproConnector.SysproTransactionService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="transactionclassSoap", Namespace="http://www.syspro.com/ns/transaction/")]
    public partial class transactionclass : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuildOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public transactionclass() {
            this.Url = global::SysproConnector.Properties.Settings.Default.SysproConnector_SysproTransactionService_transactionclass;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BuildCompletedEventHandler BuildCompleted;
        
        /// <remarks/>
        public event PostCompletedEventHandler PostCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.syspro.com/ns/transaction/Build", RequestNamespace="http://www.syspro.com/ns/transaction/", ResponseNamespace="http://www.syspro.com/ns/transaction/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Build(string UserId, string BusinessObject, string XMLIn) {
            object[] results = this.Invoke("Build", new object[] {
                        UserId,
                        BusinessObject,
                        XMLIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BuildAsync(string UserId, string BusinessObject, string XMLIn) {
            this.BuildAsync(UserId, BusinessObject, XMLIn, null);
        }
        
        /// <remarks/>
        public void BuildAsync(string UserId, string BusinessObject, string XMLIn, object userState) {
            if ((this.BuildOperationCompleted == null)) {
                this.BuildOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuildOperationCompleted);
            }
            this.InvokeAsync("Build", new object[] {
                        UserId,
                        BusinessObject,
                        XMLIn}, this.BuildOperationCompleted, userState);
        }
        
        private void OnBuildOperationCompleted(object arg) {
            if ((this.BuildCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuildCompleted(this, new BuildCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.syspro.com/ns/transaction/Post", RequestNamespace="http://www.syspro.com/ns/transaction/", ResponseNamespace="http://www.syspro.com/ns/transaction/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Post(string UserId, string BusinessObject, string XMLParameters, string XMLIn) {
            object[] results = this.Invoke("Post", new object[] {
                        UserId,
                        BusinessObject,
                        XMLParameters,
                        XMLIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PostAsync(string UserId, string BusinessObject, string XMLParameters, string XMLIn) {
            this.PostAsync(UserId, BusinessObject, XMLParameters, XMLIn, null);
        }
        
        /// <remarks/>
        public void PostAsync(string UserId, string BusinessObject, string XMLParameters, string XMLIn, object userState) {
            if ((this.PostOperationCompleted == null)) {
                this.PostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostOperationCompleted);
            }
            this.InvokeAsync("Post", new object[] {
                        UserId,
                        BusinessObject,
                        XMLParameters,
                        XMLIn}, this.PostOperationCompleted, userState);
        }
        
        private void OnPostOperationCompleted(object arg) {
            if ((this.PostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostCompleted(this, new PostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void BuildCompletedEventHandler(object sender, BuildCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuildCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuildCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PostCompletedEventHandler(object sender, PostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591